name: Minify Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: 'portfolio_v2'
          maxdepth: 2

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: main
